#! python2
#encoding: utf-8

"""
此範例唯一完整個test suite 範例
在範例裡可以看到 test suite 如何組織testcases
Loader如何加載testcases到suite
Runner 如何執行testcases和test suite 並回傳結果
另外可看到利用HTMLTestRunner 產生HTML的Report
"""

import unittest
from test1 import PythonOrgSearch
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite() #宣告test suite

    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(PythonOrgSearch)) #利用loader將 test1.py裡面定義的testcases 加載到test suite
    tests = [PythonOrgSearch('test_search_in_python_org1'), PythonOrgSearch('test_search_in_python_org2'), PythonOrgSearch('test_search_in_python_org3')]
    #另一種方式加載testcases到 test suite
    suite.addTests(tests)
    #allsuite = suite.addTests(suite1, suite2) 此行為範例，表達suite可被suite包含使用

    runner = unittest.TextTestRunner(verbosity=2) #宣告 runner，verbosity是定義log的詳細程度，預設值=1，0不會有流程敘述，2為最詳盡的log
    runner.run(suite) #run test suite

    with open('Demo_test_report.txt', 'a') as f: #產生文字檔報告
        runner2 = unittest.TextTestRunner(stream=f, verbosity=2)
        runner2.run(suite)

    with open('Demo_Html_Report.html', 'a') as f2: #產生HTML報告
        runner3 = HTMLTestRunner(stream=f2,
                                 title = 'Demo Html Report',
                                 description= 'Generated by HTMLTestRunner',
                                 verbosity=2
                                 )
        runner3.run(suite)